//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMCafeAdmin.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banquet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banquet()
        {
            this.BanquetDishes = new HashSet<BanquetDish>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string Comment { get; set; }
        public string NumberOfQuests { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public int PrepaymentId { get; set; }
        public int StatusId { get; set; }
        public decimal Service { get; set; }
        public decimal Discount { get; set; }
        public int ChangedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanquetDish> BanquetDishes { get; set; }
        public virtual BanquetStatu BanquetStatu { get; set; }
        public virtual User User { get; set; }
        public virtual PrepaymentStatus PrepaymentStatus { get; set; }
    }
}
