//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMCafeAdmin.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntity : DbContext
    {
        public DBEntity()
            : base("name=DBEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanquetDish> BanquetDishes { get; set; }
        public virtual DbSet<BanquetStatu> BanquetStatus { get; set; }
        public virtual DbSet<BookingTableStatu> BookingTableStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<BookingTable> BookingTables { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Waiter> Waiters { get; set; }
        public virtual DbSet<WatersSchedule> WatersSchedules { get; set; }
        public virtual DbSet<Banquet> Banquets { get; set; }
        public virtual DbSet<DishType> DishTypes { get; set; }
        public virtual DbSet<PrepaymentStatus> PrepaymentStatuses { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<TablePosition> TablePositions { get; set; }
        public virtual DbSet<RestTable> RestTables { get; set; }
    }
}
