//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMCafeAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatersSchedule
    {
        public int Id { get; set; }
        public int WaterId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public int ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
